import { Meta } from '@storybook/react';
declare const meta: Meta;
export default meta;
export declare const Primary: import('@storybook/csf').StoryAnnotations<import('@storybook/react').ReactRenderer, {}, {}>;
export declare const PrimaryRound: import('@storybook/csf').StoryAnnotations<import('@storybook/react').ReactRenderer, {}, {}>;
export declare const Secondary: import('@storybook/csf').StoryAnnotations<import('@storybook/react').ReactRenderer, {}, {}>;
export declare const SecondaryRound: import('@storybook/csf').StoryAnnotations<import('@storybook/react').ReactRenderer, {}, {}>;
export declare const Success: import('@storybook/csf').StoryAnnotations<import('@storybook/react').ReactRenderer, {}, {}>;
export declare const SuccessRound: import('@storybook/csf').StoryAnnotations<import('@storybook/react').ReactRenderer, {}, {}>;
export declare const Danger: import('@storybook/csf').StoryAnnotations<import('@storybook/react').ReactRenderer, {}, {}>;
export declare const DangerRound: import('@storybook/csf').StoryAnnotations<import('@storybook/react').ReactRenderer, {}, {}>;
export declare const Warning: import('@storybook/csf').StoryAnnotations<import('@storybook/react').ReactRenderer, {}, {}>;
export declare const WarningRound: import('@storybook/csf').StoryAnnotations<import('@storybook/react').ReactRenderer, {}, {}>;
export declare const Info: import('@storybook/csf').StoryAnnotations<import('@storybook/react').ReactRenderer, {}, {}>;
export declare const InfoRound: import('@storybook/csf').StoryAnnotations<import('@storybook/react').ReactRenderer, {}, {}>;
export declare const Light: import('@storybook/csf').StoryAnnotations<import('@storybook/react').ReactRenderer, {}, {}>;
export declare const LightRound: import('@storybook/csf').StoryAnnotations<import('@storybook/react').ReactRenderer, {}, {}>;
export declare const Dark: import('@storybook/csf').StoryAnnotations<import('@storybook/react').ReactRenderer, {}, {}>;
export declare const DarkRound: import('@storybook/csf').StoryAnnotations<import('@storybook/react').ReactRenderer, {}, {}>;
export declare const Link: import('@storybook/csf').StoryAnnotations<import('@storybook/react').ReactRenderer, {}, {}>;
export declare const LinkRound: import('@storybook/csf').StoryAnnotations<import('@storybook/react').ReactRenderer, {}, {}>;
